/* ---------- Built-in content ----------
   Generated by tools/build-seed.py from a backup file. Don't hand-edit:
   change things in the browser, hit "Back up", and run the script again.

   These are the recipes and glossary the site loads on first open in any
   browser, in this exact order. Photos are real files in ./media/, linked by
   relative path. Anything added, edited, reordered or deleted in a browser
   after that lives in IndexedDB and takes precedence over what's here. */

const SEED_RECIPES = [
  {
    "id": "ec237f37-2ac9-42b7-9fb2-f62f376ff313",
    "nameEn": "Hainanese Yi Bua Kueh (Coconut Palm Sugar Steamed Cake)",
    "nameCn": "薏粑",
    "story": "Yi bua (薏粑) is my mum's favourite childhood kueh! It is a Hainanese kueh made with glutinous rice flour dough and filled with mixture of grated coconut, gula Melaka, toasted peanuts, toasted sesame seeds, and grated ginger. The dough has a mochi-like texture, soft and chewy.",
    "ingredients": [],
    "steps": [],
    "order": 0,
    "createdAt": 1785230804163,
    "media": [
      {
        "id": "hainanese-yi-bua-kueh-co-1",
        "type": "image",
        "name": "hainanese-yi-bua-kueh-co-1.jpg",
        "src": "./media/hainanese-yi-bua-kueh-co-1.jpg"
      },
      {
        "id": "hainanese-yi-bua-kueh-co-2",
        "type": "image",
        "name": "hainanese-yi-bua-kueh-co-2.jpg",
        "src": "./media/hainanese-yi-bua-kueh-co-2.jpg"
      }
    ]
  },
  {
    "id": "84fbd0dc-0e81-40d0-8868-4ce6e717020a",
    "nameEn": "Orh Kueh / Yam Cake",
    "nameCn": "芋头糕",
    "story": "Orh Kueh! Aka Yam Cake/芋头糕 is one of my favourite home made food by my mum! Whenever there is a gathering with my extended family, she will prepare this dish! Taste super delicious when freshly made or lightly fried with egg batter is the best way to have it! 😋",
    "ingredients": [
      {
        "her": "芋头一颗",
        "mine": "Yam - 800g"
      },
      {
        "her": "虾米 80g",
        "mine": "Shrimp - 80g"
      },
      {
        "her": "冬菇八朵",
        "mine": "8 Dried Mushrooms"
      },
      {
        "her": "腊肠两条",
        "mine": "2 piece of cured sausage"
      },
      {
        "her": "粘米粉 500g",
        "mine": "Rice flour 500g"
      },
      {
        "her": "木薯粉 100g",
        "mine": "Tapioca flour 100G"
      },
      {
        "her": "葱头子十立",
        "mine": "10 shallots"
      },
      {
        "her": "1.5L 开水",
        "mine": "1.5 L Water"
      },
      {
        "her": "3 茶匙盐",
        "mine": "3 teaspoon salt"
      },
      {
        "her": "胡椒粉少许",
        "mine": "Sprinkle of pepper"
      },
      {
        "her": "麻油一汤匙",
        "mine": "1 table spoon Sesame oil"
      }
    ],
    "steps": [
      "Soak dried mushrooms in water for an hour to soften it",
      "Dice all the ingredients into cube (Yam, mushrooms, cured sausage and shrimps)",
      "Chop and fried shallots in 3 tablespoons of cooking oil",
      "Set aside the shallots and stir fried the ingredients individually (Yam first, shrimp, mushroom, curated sausage)",
      "In a big bowl, add rice flour, tapioca flour and water to mix well, add salt, pepper, sesame oil",
      "Add all ingredients to the flour/water mixture into big wok",
      "Cook the mixture in light heat until it congregate",
      "Oil the metal tray",
      "Pour the mixture into metal tray and steam for 45mins"
    ],
    "order": 1,
    "createdAt": 1785209869544,
    "media": [
      {
        "id": "orh-kueh-yam-cake-1",
        "type": "image",
        "name": "orh-kueh-yam-cake-1.jpg",
        "src": "./media/orh-kueh-yam-cake-1.jpg"
      },
      {
        "id": "orh-kueh-yam-cake-2",
        "type": "image",
        "name": "orh-kueh-yam-cake-2.jpg",
        "src": "./media/orh-kueh-yam-cake-2.jpg"
      },
      {
        "id": "orh-kueh-yam-cake-3",
        "type": "image",
        "name": "orh-kueh-yam-cake-3.jpg",
        "src": "./media/orh-kueh-yam-cake-3.jpg"
      },
      {
        "id": "orh-kueh-yam-cake-4",
        "type": "image",
        "name": "orh-kueh-yam-cake-4.jpg",
        "src": "./media/orh-kueh-yam-cake-4.jpg"
      },
      {
        "id": "orh-kueh-yam-cake-5",
        "type": "image",
        "name": "orh-kueh-yam-cake-5.jpg",
        "src": "./media/orh-kueh-yam-cake-5.jpg"
      },
      {
        "id": "orh-kueh-yam-cake-6",
        "type": "image",
        "name": "orh-kueh-yam-cake-6.jpg",
        "src": "./media/orh-kueh-yam-cake-6.jpg"
      },
      {
        "id": "orh-kueh-yam-cake-7",
        "type": "image",
        "name": "orh-kueh-yam-cake-7.jpg",
        "src": "./media/orh-kueh-yam-cake-7.jpg"
      },
      {
        "id": "orh-kueh-yam-cake-8",
        "type": "image",
        "name": "orh-kueh-yam-cake-8.jpg",
        "src": "./media/orh-kueh-yam-cake-8.jpg"
      },
      {
        "id": "orh-kueh-yam-cake-9",
        "type": "image",
        "name": "orh-kueh-yam-cake-9.jpg",
        "src": "./media/orh-kueh-yam-cake-9.jpg"
      }
    ]
  },
  {
    "id": "bce4bd31-c5af-41a6-aa0e-8002fe869502",
    "nameEn": "Tang yuan / Glutinous rice ball",
    "nameCn": "汤圆",
    "story": "During 冬至，winter solace or 元宵节，during chinese new year period, my mum will always make tang yuan for the family to signify 一家团圆， family reunion.",
    "ingredients": [
      {
        "her": "糯米粉",
        "mine": "Glutinous rice flour"
      },
      {
        "her": "开水",
        "mine": "Water"
      },
      {
        "her": "红色素",
        "mine": "Red colouring"
      },
      {
        "her": "斑斓叶",
        "mine": "Pandan leafs"
      },
      {
        "her": "红糖",
        "mine": "Red sugar"
      }
    ],
    "steps": [
      "Mix water with glutinous rice flour and knead into dough (Add red colouring if required)",
      "Divide the dough into smaller pieces and roll them into balls",
      "Boil pandan leafs in water for 10mins, and add the Glutinous rice balls in",
      "Add red sugar to the soup as required"
    ],
    "order": 2,
    "createdAt": 1785214724657,
    "media": [
      {
        "id": "tang-yuan-glutinous-rice-1",
        "type": "image",
        "name": "tang-yuan-glutinous-rice-1.jpg",
        "src": "./media/tang-yuan-glutinous-rice-1.jpg"
      },
      {
        "id": "tang-yuan-glutinous-rice-2",
        "type": "image",
        "name": "tang-yuan-glutinous-rice-2.jpg",
        "src": "./media/tang-yuan-glutinous-rice-2.jpg"
      },
      {
        "id": "tang-yuan-glutinous-rice-3",
        "type": "image",
        "name": "tang-yuan-glutinous-rice-3.jpg",
        "src": "./media/tang-yuan-glutinous-rice-3.jpg"
      },
      {
        "id": "tang-yuan-glutinous-rice-4",
        "type": "image",
        "name": "tang-yuan-glutinous-rice-4.jpg",
        "src": "./media/tang-yuan-glutinous-rice-4.jpg"
      }
    ]
  }
];

const SEED_GLOSSARY = [
  {
    "term": "一把 (a handful)",
    "meaning": "~30g"
  },
  {
    "term": "少许 (a little)",
    "meaning": "~1/4 tsp"
  },
  {
    "term": "$2 worth of ginger",
    "meaning": "a thumb-sized knob, ~15g"
  }
];
