/* ---------- Built-in content ----------
   Generated by tools/build-seed.py from a backup file. Don't hand-edit:
   change things in the browser, hit "Back up", and run the script again.

   These are the recipes and glossary the site loads on first open in any
   browser, in this exact order. Photos are real files in ./media/, linked by
   relative path. Anything added, edited, reordered or deleted in a browser
   after that lives in IndexedDB and takes precedence over what's here. */

const SEED_RECIPES = [
  {
    "id": "84fbd0dc-0e81-40d0-8868-4ce6e717020a",
    "nameEn": "Orh Kueh / Yam Cake",
    "nameCn": "芋头糕",
    "story": "Orh Kueh! Aka Yam Cake/芋头糕 is one of my favourite home made food by my mum! Whenever there is a gathering with my extended family, she will prepare this dish! Taste super delicious when freshly made or lightly fried with egg batter is the best way to have it! 😋",
    "ingredients": [
      {
        "her": "芋头一颗",
        "mine": "Yam - 800g"
      },
      {
        "her": "虾米 80g",
        "mine": "Shrimp - 80g"
      },
      {
        "her": "冬菇八朵",
        "mine": "8 Dried Mushrooms"
      },
      {
        "her": "腊肠两条",
        "mine": "2 piece of cured sausage"
      },
      {
        "her": "粘米粉 500g",
        "mine": "Rice flour 500g"
      },
      {
        "her": "木薯粉 100g",
        "mine": "Tapioca flour 100G"
      },
      {
        "her": "葱头子十立",
        "mine": "10 shallots"
      },
      {
        "her": "1.5L 开水",
        "mine": "1.5 L Water"
      },
      {
        "her": "3 茶匙盐",
        "mine": "3 teaspoon salt"
      },
      {
        "her": "胡椒粉少许",
        "mine": "Sprinkle of pepper"
      },
      {
        "her": "麻油一汤匙",
        "mine": "1 table spoon Sesame oil"
      }
    ],
    "steps": [
      "Soak dried mushrooms in water for an hour to soften it",
      "Dice all the ingredients into cube (Yam, mushrooms, cured sausage and shrimps)",
      "Chop and fried shallots in 3 tablespoons of cooking oil",
      "Set aside the shallots and stir fried the ingredients individually (Yam first, shrimp, mushroom, cured sausage)",
      "In a big bowl, add rice flour, tapioca flour and water to mix well, add salt, pepper, sesame oil",
      "Add all ingredients to the flour/water mixture into big wok",
      "Cook the mixture in light heat until it congregate",
      "Oil the metal tray",
      "Pour the mixture into metal tray and steam for 45mins"
    ],
    "order": 0,
    "createdAt": 1785209869544,
    "media": [
      {
        "thumb": "./media/thumbs/orh-kueh-yam-cake-1.jpg",
        "id": "orh-kueh-yam-cake-1",
        "type": "image",
        "name": "Yam Cake! Orh Kueh!",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-1.jpg"
      },
      {
        "thumb": "./media/thumbs/orh-kueh-yam-cake-2.jpg",
        "id": "orh-kueh-yam-cake-2",
        "type": "image",
        "name": "Cutting Yam into slices",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-2.jpg"
      },
      {
        "thumb": "./media/thumbs/orh-kueh-yam-cake-3.jpg",
        "id": "orh-kueh-yam-cake-3",
        "type": "image",
        "name": "Ingredients all chopped nicely",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-3.jpg"
      },
      {
        "thumb": "./media/thumbs/orh-kueh-yam-cake-4.jpg",
        "id": "orh-kueh-yam-cake-4",
        "type": "image",
        "name": "Stir frying shrimps",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-4.jpg"
      },
      {
        "thumb": "./media/thumbs/orh-kueh-yam-cake-5.jpg",
        "id": "orh-kueh-yam-cake-5",
        "type": "image",
        "name": "Mixing of flour mixtures and ingredients",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-5.jpg"
      },
      {
        "thumb": "./media/thumbs/orh-kueh-yam-cake-6.jpg",
        "id": "orh-kueh-yam-cake-6",
        "type": "image",
        "name": "Add the mixture to a large wok",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-6.jpg"
      },
      {
        "poster": "./media/orh-kueh-yam-cake-7-poster.jpg",
        "id": "orh-kueh-yam-cake-7",
        "type": "video",
        "name": "Stir well as it cooks",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-7.mp4"
      },
      {
        "thumb": "./media/thumbs/orh-kueh-yam-cake-8.jpg",
        "id": "orh-kueh-yam-cake-8",
        "type": "image",
        "name": "Pour the cooked mixture into a metal tray and smooth the top",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-8.jpg"
      },
      {
        "thumb": "./media/thumbs/orh-kueh-yam-cake-9.jpg",
        "id": "orh-kueh-yam-cake-9",
        "type": "image",
        "name": "Smooth the cooked mixture",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-9.jpg"
      },
      {
        "thumb": "./media/thumbs/orh-kueh-yam-cake-10.jpg",
        "id": "orh-kueh-yam-cake-10",
        "type": "image",
        "name": "Orh Kueh handwritten recipe",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-10.jpg"
      },
      {
        "id": "orh-kueh-yam-cake-11",
        "type": "audio",
        "name": "芋头糕/Yam cake recipe",
        "description": "",
        "src": "./media/orh-kueh-yam-cake-11.m4a"
      }
    ]
  },
  {
    "id": "1c4e528c-d621-4ed0-8a29-f4e21f8166b2",
    "nameEn": "Fried Honeycomb",
    "nameCn": "炸蜂窝",
    "story": "During chinese new year, it's a tradition that my mum would make this new year goodies for our relative and friends! Always my cousin's favourite CNY snacks!",
    "ingredients": [
      {
        "her": "粘米粉 300g",
        "mine": "Rice flour 300g"
      },
      {
        "her": "鸡蛋3粒",
        "mine": "3 eggs"
      },
      {
        "her": "椰浆 200ml",
        "mine": "Coconut milk 200ml"
      },
      {
        "her": "香兰叶汁 1/4 tsp",
        "mine": "Pandan leaf juice 1/4 tsp"
      },
      {
        "her": "糖 180g",
        "mine": "Sugar 180g"
      },
      {
        "her": "盐1/2 tsp",
        "mine": "1/2 tsp salt"
      },
      {
        "her": "花生油 1.5 litre",
        "mine": "1.5 litre Peanut cooking oil"
      }
    ],
    "steps": [
      "Add  all ingredient (rice flour, eggs, coconut milk, pandan leaf juice, sugar and salt) into a big bowl and mix well",
      "Pour the cooking oil into the wok and dip the iron honeycomb moulds. Turn on the stove to heat up the iron mould",
      "Wait till the oil is hot enough, dip the honeycomb mould into the batter. (Note just dip to the height of the mould, not the entire thing)",
      "Allow the batter to stick to the mould and fry it in hot oil. Shake lightly for the batter to come off the mould",
      "Flip the honeycomb and fried till golden brown"
    ],
    "order": 1,
    "createdAt": 1787502951009,
    "media": [
      {
        "thumb": "./media/thumbs/fried-honeycomb-1.jpg",
        "id": "fried-honeycomb-1",
        "type": "image",
        "name": "Fried honeycomb",
        "description": "",
        "src": "./media/fried-honeycomb-1.jpg"
      },
      {
        "thumb": "./media/thumbs/fried-honeycomb-2.jpg",
        "id": "fried-honeycomb-2",
        "type": "image",
        "name": "Ingredients: Egg, pandan extract, flour",
        "description": "",
        "src": "./media/fried-honeycomb-2.jpg"
      },
      {
        "thumb": "./media/thumbs/fried-honeycomb-3.jpg",
        "id": "fried-honeycomb-3",
        "type": "image",
        "name": "Frying in progress",
        "description": "",
        "src": "./media/fried-honeycomb-3.jpg"
      },
      {
        "thumb": "./media/thumbs/fried-honeycomb-4.jpg",
        "id": "fried-honeycomb-4",
        "type": "image",
        "name": "Fried honeycombs",
        "description": "",
        "src": "./media/fried-honeycomb-4.jpg"
      },
      {
        "poster": "./media/fried-honeycomb-5-poster.jpg",
        "id": "fried-honeycomb-5",
        "type": "video",
        "name": "Frying in progress",
        "description": "",
        "src": "./media/fried-honeycomb-5.mp4"
      },
      {
        "thumb": "./media/thumbs/fried-honeycomb-6.jpg",
        "id": "fried-honeycomb-6",
        "type": "image",
        "name": "Hand written recipe by my mum",
        "description": "",
        "src": "./media/fried-honeycomb-6.jpg"
      },
      {
        "id": "fried-honeycomb-7",
        "type": "audio",
        "name": "炸蜂窝 Fried honeycomb recipe",
        "description": "",
        "src": "./media/fried-honeycomb-7.m4a"
      }
    ]
  },
  {
    "id": "ec237f37-2ac9-42b7-9fb2-f62f376ff313",
    "nameEn": "Hainanese Yi Bua Kueh (Coconut Palm Sugar Steamed Cake)",
    "nameCn": "薏粑",
    "story": "Yi bua (薏粑) is my mum's favourite childhood kueh! It is a Hainanese kueh made with glutinous rice flour dough and filled with mixture of grated coconut, gula Melaka, toasted peanuts, toasted sesame seeds, and grated ginger. The dough has a mochi-like texture, soft and chewy.",
    "ingredients": [
      {
        "her": "香蕉叶",
        "mine": "Banana leaves"
      },
      {
        "her": "斑斓叶",
        "mine": "Pandan leaves"
      },
      {
        "her": "糯米粉 250g",
        "mine": "Glutinous rice flour 250g"
      },
      {
        "her": "木薯粉 20g",
        "mine": "Tapioca flour 20g"
      },
      {
        "her": "水 250 ml",
        "mine": "Water 250ml"
      },
      {
        "her": "油两汤匙",
        "mine": "Oil 2 tbsp"
      },
      {
        "her": "椰糖一粒",
        "mine": "Gula melaka (Palm sugar) 70g"
      },
      {
        "her": "芝麻 20g",
        "mine": "Sesame 20g"
      },
      {
        "her": "花生 20g",
        "mine": "Ground Peanut 20g"
      },
      {
        "her": "椰子一粒",
        "mine": "1 Grated coconut"
      },
      {
        "her": "橙皮少许剪小粒",
        "mine": "Dried orange peels cut into small bits"
      }
    ],
    "steps": [
      "Cut banana leaf into 6inch in length and 2.5 inch in width",
      "For dough: Add glutinous rice flour, tapioca flour, 250ml water and 2 tbsp oil into a metal bowl and knead into dough",
      "For fillings: Break palm sugar into smaller pieces, add 4 tbsp water into a pot cook and melt it",
      "Add in pandan leaves into melted palm sugar and cook to extract pandan flavour.",
      "Remove pandan leaves, add in grated coconut continue to cook and mix well with melted palm sugar",
      "Remove mixture from heat and add in ground peanuts, sesame and dried orange peels. Mix well",
      "Divide the dough into smaller pieces (roughly about 40g per piece)",
      "Press the dough flat and wrap with 2 tbsp of filling",
      "Wrap the filled dough with banana leaf",
      "Steam for 10mins and it's ready!"
    ],
    "order": 2,
    "createdAt": 1785230804163,
    "media": [
      {
        "thumb": "./media/thumbs/hainanese-yi-bua-kueh-co-1.jpg",
        "id": "hainanese-yi-bua-kueh-co-1",
        "type": "image",
        "name": "Yi Bua!",
        "description": "The finish product here!",
        "src": "./media/hainanese-yi-bua-kueh-co-1.jpg"
      },
      {
        "thumb": "./media/thumbs/hainanese-yi-bua-kueh-co-2.jpg",
        "id": "hainanese-yi-bua-kueh-co-2",
        "type": "image",
        "name": "Proud mum with her creation",
        "description": "",
        "src": "./media/hainanese-yi-bua-kueh-co-2.jpg"
      },
      {
        "thumb": "./media/thumbs/hainanese-yi-bua-kueh-co-3.jpg",
        "id": "hainanese-yi-bua-kueh-co-3",
        "type": "image",
        "name": "Handwritten recipe for Yi Bua",
        "description": "",
        "src": "./media/hainanese-yi-bua-kueh-co-3.jpg"
      },
      {
        "id": "hainanese-yi-bua-kueh-co-4",
        "type": "audio",
        "name": "薏粑 Yi bua recipe",
        "description": "",
        "src": "./media/hainanese-yi-bua-kueh-co-4.m4a"
      }
    ]
  },
  {
    "id": "bce4bd31-c5af-41a6-aa0e-8002fe869502",
    "nameEn": "Tang Yuan / Glutinous Rice Ball",
    "nameCn": "汤圆",
    "story": "During 冬至, winter solstice or 元宵节, during the Chinese New Year period, my mum will always make tang yuan for the family to signify 一家团圆, family reunion.",
    "ingredients": [
      {
        "her": "糯米粉",
        "mine": "Glutinous rice flour"
      },
      {
        "her": "开水",
        "mine": "Water"
      },
      {
        "her": "红色素",
        "mine": "Red colouring"
      },
      {
        "her": "斑斓叶",
        "mine": "Pandan leaves"
      },
      {
        "her": "红糖",
        "mine": "Red sugar"
      }
    ],
    "steps": [
      "Mix water with glutinous rice flour and knead into dough (Add red colouring if required)",
      "Divide the dough into smaller pieces and roll them into balls",
      "Boil pandan leaves in water for 10mins, and add the Glutinous rice balls in",
      "Add red sugar to the soup as required"
    ],
    "order": 3,
    "createdAt": 1785214724657,
    "media": [
      {
        "thumb": "./media/thumbs/tang-yuan-glutinous-rice-1.jpg",
        "id": "tang-yuan-glutinous-rice-1",
        "type": "image",
        "name": "Tang Yuan!",
        "description": "",
        "src": "./media/tang-yuan-glutinous-rice-1.jpg"
      },
      {
        "thumb": "./media/thumbs/tang-yuan-glutinous-rice-2.jpg",
        "id": "tang-yuan-glutinous-rice-2",
        "type": "image",
        "name": "Pink and white dough and pandan leaf",
        "description": "",
        "src": "./media/tang-yuan-glutinous-rice-2.jpg"
      },
      {
        "thumb": "./media/thumbs/tang-yuan-glutinous-rice-3.jpg",
        "id": "tang-yuan-glutinous-rice-3",
        "type": "image",
        "name": "Rolled tang yuan",
        "description": "",
        "src": "./media/tang-yuan-glutinous-rice-3.jpg"
      },
      {
        "poster": "./media/tang-yuan-glutinous-rice-4-poster.jpg",
        "id": "tang-yuan-glutinous-rice-4",
        "type": "video",
        "name": "Pink and white rolled tang yuan",
        "description": "",
        "src": "./media/tang-yuan-glutinous-rice-4.mp4"
      },
      {
        "thumb": "./media/thumbs/tang-yuan-glutinous-rice-5.jpg",
        "id": "tang-yuan-glutinous-rice-5",
        "type": "image",
        "name": "Cooking rolled tang yuan",
        "description": "",
        "src": "./media/tang-yuan-glutinous-rice-5.jpg"
      },
      {
        "id": "tang-yuan-glutinous-rice-6",
        "type": "audio",
        "name": "汤圆 Tang Yuan recipe",
        "description": "",
        "src": "./media/tang-yuan-glutinous-rice-6.m4a"
      },
      {
        "thumb": "./media/thumbs/tang-yuan-glutinous-rice-7.jpg",
        "id": "tang-yuan-glutinous-rice-7",
        "type": "image",
        "name": "Tang yuan handwritten recipe",
        "description": "",
        "src": "./media/tang-yuan-glutinous-rice-7.jpg"
      }
    ]
  }
];

const SEED_GLOSSARY = [
  {
    "term": "两块钱小辣椒",
    "meaning": "$2 worth of chili padi (~150g, a small bag)"
  },
  {
    "term": "两块姜",
    "meaning": "2 knobs of ginger, each about thumb-sized (~30g total)"
  },
  {
    "term": "一把",
    "meaning": "a handful  ~30g"
  },
  {
    "term": "少许",
    "meaning": "a little  ~1/4 tsp"
  },
  {
    "term": "一大汤匙",
    "meaning": "about 2 tbsp"
  },
  {
    "term": "一点点",
    "meaning": "1/2 tbsp"
  }
];
