#!/usr/bin/env python3
"""Turn a Taste of Home backup file into the project's built-in content.

Usage:  python3 tools/build-seed.py ~/Downloads/taste-of-home-backup-2026-08-24.json

Reads a backup exported with the site's "Back up" button and rewrites
./media/ and ./recipes-seed.js so the recipes, their order, their photos and
the glossary all ship inside the project folder. Photos are resized to
1600px JPEGs, so the folder stays small enough to zip and send.
"""

import base64
import json
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_DIR = os.path.join(ROOT, 'media')
SEED_FILE = os.path.join(ROOT, 'recipes-seed.js')

IMAGE_EXT = {'image/png': 'png', 'image/jpeg': 'jpg', 'image/heic': 'heic', 'image/webp': 'webp'}
VIDEO_EXT = {'video/quicktime': 'mov', 'video/mp4': 'mp4', 'video/webm': 'webm'}


def slug(text):
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')[:24].strip('-')


def main():
    if len(sys.argv) != 2:
        sys.exit('Usage: python3 tools/build-seed.py <backup.json>')

    backup_path = os.path.expanduser(sys.argv[1])
    with open(backup_path) as f:
        data = json.load(f)

    if data.get('app') != 'tasteOfHome':
        sys.exit('That file does not look like a Taste of Home backup.')

    # Start from a clean media folder so deleted photos don't linger in the zip.
    if os.path.isdir(MEDIA_DIR):
        shutil.rmtree(MEDIA_DIR)
    os.makedirs(MEDIA_DIR)

    recipes = sorted(data['recipes'], key=lambda r: r.get('order', 0))
    out = []

    for position, recipe in enumerate(recipes):
        name = slug(recipe['nameEn'])
        media_out = []

        for index, item in enumerate(recipe.get('media', []), 1):
            header, encoded = item['dataUrl'].split(',', 1)
            mime = header[5:].split(';')[0]
            raw_ext = IMAGE_EXT.get(mime) or VIDEO_EXT.get(mime) or 'bin'
            raw_path = os.path.join(MEDIA_DIR, f'raw-{name}-{index}.{raw_ext}')
            with open(raw_path, 'wb') as f:
                f.write(base64.b64decode(encoded))

            if mime in VIDEO_EXT:
                final_name = f'{name}-{index}.{raw_ext}'
                os.rename(raw_path, os.path.join(MEDIA_DIR, final_name))
            else:
                final_name = f'{name}-{index}.jpg'
                subprocess.run(
                    ['sips', '-s', 'format', 'jpeg', '-s', 'formatOptions', '80',
                     '-Z', '1600', raw_path, '--out', os.path.join(MEDIA_DIR, final_name)],
                    check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
                os.remove(raw_path)

            media_out.append({
                'id': f'{name}-{index}',
                'type': item.get('type', 'image'),
                'name': final_name,
                'src': f'./media/{final_name}',
            })

        out.append({
            'id': recipe['id'],
            'nameEn': recipe['nameEn'],
            'nameCn': recipe.get('nameCn', ''),
            'story': recipe.get('story', ''),
            'ingredients': recipe.get('ingredients', []),
            'steps': recipe.get('steps', []),
            'order': position,
            'createdAt': recipe.get('createdAt'),
            'media': media_out,
        })

    glossary = [{'term': e['term'], 'meaning': e['meaning']} for e in data.get('glossary', [])]

    header = """/* ---------- Built-in content ----------
   Generated by tools/build-seed.py from a backup file. Don't hand-edit:
   change things in the browser, hit "Back up", and run the script again.

   These are the recipes and glossary the site loads on first open in any
   browser, in this exact order. Photos are real files in ./media/, linked by
   relative path. Anything added, edited, reordered or deleted in a browser
   after that lives in IndexedDB and takes precedence over what's here. */

const SEED_RECIPES = """

    body = json.dumps(out, ensure_ascii=False, indent=2)
    gloss = json.dumps(glossary, ensure_ascii=False, indent=2)

    with open(SEED_FILE, 'w') as f:
        f.write(header + body + ';\n\nconst SEED_GLOSSARY = ' + gloss + ';\n')

    total_media = sum(len(r['media']) for r in out)
    size_mb = sum(
        os.path.getsize(os.path.join(MEDIA_DIR, n)) for n in os.listdir(MEDIA_DIR)
    ) / 1024 / 1024

    print(f'{len(out)} recipes, {len(glossary)} glossary entries, {total_media} media files ({size_mb:.1f} MB)')
    for r in out:
        print(f"  {r['order'] + 1}. {r['nameEn']} — {len(r['ingredients'])} ingredients, "
              f"{len(r['steps'])} steps, {len(r['media'])} photos")


if __name__ == '__main__':
    main()
